version: "3.7"
services:
  db:
    container_name: pg_container_dev
    image: postgres
    env_file:
      - ./server/.env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4_container_dev
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
